[Server]
    BindHost = "localhost"
    BindPort = 9000
#    CORSOrigins = "*"
#    Debug = true

[Paging]
    LimitDefault = 10
    LimitMax = 1000

[Metadata]
	Title = "pg-featureserv Demo"
	Description = "Demo of Crunchy Data PostGIS Feature Server"
